### PR TITLE
Primary xml generation improvements

### PR DESCRIPTION
**Pull request by Sammers21**
Ready to be reviewed

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Sammers21 next time, please make sure your PR descriptions contains the number of the issue you are working with

**Comment by yegor256** [comment]
@Sammers21 thanks!

**Comment by Sammers21** [comment]
> @Sammers21 next time, please make sure your PR description contains the number of the issue you are working with

Ok

**Pull request merged**
